### ISSUE TITLE
Not working with Rails 6

### ISSUE THREAD

**Issue by AquisTech** [AquisTech/has_contact_number#1]
Not working with Rails 6 and possibly may not work with Rails 5
```
ArgumentError (Passing string to be evaluated in :if and :unless conditional options is not supported. Pass a symbol for an instance method, or a lambda, proc or block, instead.):
  
(eval):15:in `define_methods_for'
```
Full trace
```
(eval):15:in `define_methods_for'
/home/anand/projects/has_contact_number/lib/has_contact_number/model_methods.rb:16:in `class_eval'
/home/anand/projects/has_contact_number/lib/has_contact_number/model_methods.rb:16:in `define_methods_for'
/home/anand/projects/has_contact_number/lib/has_contact_number/model_methods.rb:10:in `block in contact_number_attributes'
/home/anand/projects/has_contact_number/lib/has_contact_number/model_methods.rb:8:in `each'
/home/anand/projects/has_contact_number/lib/has_contact_number/model_methods.rb:8:in `contact_number_attributes'
```

**Comment by AquisTech** [comment]
Fixed with PR#2
